"""add traceable identity registration decisions

Revision ID: a805e70f2e08
Revises: d25819f4b100
Create Date: 2026-10-06 05:01:47.491335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a805e70f2e08'
down_revision: Union[str, Sequence[str], None] = 'd25819f4b100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_registration_decision',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('raw_record_id', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('previous_decision_id', sa.UUID(), nullable=True),
    sa.Column('previous_version_number', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=True),
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('source_confirmation_id', sa.String(length=100), nullable=False),
    sa.Column('source_confirmation_sha256', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('normalization_profile', sa.String(length=50), nullable=False),
    sa.Column('code_revision', sa.String(length=40), nullable=False),
    sa.Column('evidence_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                outcome IN ('CREATED', 'MATCHED')\n                AND officer_uid IS NOT NULL\n            )\n            OR\n            (\n                outcome = 'REVIEW_REQUIRED'\n                AND officer_uid IS NULL\n            )\n            ", name=op.f('ck_identity_registration_decision_decision_officer_binding')),
    sa.CheckConstraint("code_revision ~ '^[0-9a-f]{40}$'", name=op.f('ck_identity_registration_decision_decision_code_revision')),
    sa.CheckConstraint("outcome IN ('CREATED', 'MATCHED', 'REVIEW_REQUIRED')", name=op.f('ck_identity_registration_decision_decision_outcome')),
    sa.CheckConstraint("reason_code ~ '^[A-Z][A-Z0-9_]{0,79}$'", name=op.f('ck_identity_registration_decision_decision_reason_code')),
    sa.CheckConstraint("source_confirmation_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_identity_registration_decision_decision_confirmation_sha256')),
    sa.CheckConstraint('\n            (\n                version_number = 1\n                AND previous_decision_id IS NULL\n                AND previous_version_number IS NULL\n            )\n            OR\n            (\n                version_number > 1\n                AND previous_decision_id IS NOT NULL\n                AND previous_version_number IS NOT NULL\n                AND previous_version_number > 0\n                AND version_number = previous_version_number + 1\n            )\n            ', name=op.f('ck_identity_registration_decision_decision_version_chain')),
    sa.CheckConstraint('\n            length(trim(source_confirmation_id)) > 0\n            AND length(trim(policy_version)) > 0\n            AND length(trim(normalization_profile)) > 0\n            AND length(trim(encryption_key_version)) > 0\n            ', name=op.f('ck_identity_registration_decision_decision_required_metadata')),
    sa.CheckConstraint('octet_length(evidence_ciphertext) > 28', name=op.f('ck_identity_registration_decision_decision_encrypted_evidence')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_identity_registration_decision_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_decision_id', 'raw_record_id', 'previous_version_number'], ['staging.identity_registration_decision.decision_id', 'staging.identity_registration_decision.raw_record_id', 'staging.identity_registration_decision.version_number'], name='fk_identity_decision_previous', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_record_id'], ['staging.raw_record.raw_record_id'], name=op.f('fk_identity_registration_decision_raw_record_id_raw_record'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['identity.source_system.source_system_id'], name=op.f('fk_identity_registration_decision_source_system_id_source_system'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_identity_registration_decision')),
    sa.UniqueConstraint('decision_id', 'raw_record_id', 'version_number', name='uq_identity_decision_version_binding'),
    sa.UniqueConstraint('previous_decision_id', name='uq_identity_decision_previous'),
    sa.UniqueConstraint('raw_record_id', 'version_number', name='uq_identity_decision_row_version'),
    schema='staging'
    )
    # ### end Alembic commands ###

    # Remove any default grants before granting the application's exact access.
    op.execute(
        "REVOKE ALL ON TABLE staging.identity_registration_decision "
        "FROM PUBLIC"
    )
    op.execute(
        "REVOKE ALL ON TABLE staging.identity_registration_decision "
        "FROM police_identity_app"
    )
    op.execute(
        "GRANT SELECT, INSERT ON TABLE staging.identity_registration_decision "
        "TO police_identity_app"
    )

def downgrade() -> None:
    """Remove the decision table only when it contains no evidence."""

    # Prevent concurrent inserts between the emptiness check and removal.
    op.execute(
        "LOCK TABLE staging.identity_registration_decision "
        "IN ACCESS EXCLUSIVE MODE"
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM staging.identity_registration_decision
            ) THEN
                RAISE EXCEPTION
                    'Cannot downgrade populated identity decisions; '
                    'preserve decision evidence first.';
            END IF;
        END;
        $$
        """
    )

    # Remove only this empty table; never cascade to other evidence tables.
    op.drop_table("identity_registration_decision", schema="staging")
