"""create protected identity master schema

Revision ID: bd872fe5ccc0
Revises:
Create Date: 2026-09-27 14:47:01.101149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd872fe5ccc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer',
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('registry_state', sa.String(length=20), server_default=sa.text("'REGISTERED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("registry_state IN ('REGISTERED', 'MERGED', 'ARCHIVED')", name=op.f('ck_officer_officer_registry_state')),
    sa.PrimaryKeyConstraint('officer_uid', name=op.f('pk_officer')),
    schema='identity'
    )
    op.create_table('source_system',
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('source_system_code', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source_system_id', name=op.f('pk_source_system')),
    sa.UniqueConstraint('source_system_code', name=op.f('uq_source_system_source_system_code')),
    schema='identity'
    )
    op.create_table('source_assertion',
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('assertion_type', sa.String(length=50), nullable=False),
    sa.Column('asserted_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_record_id', sa.String(length=150), nullable=True),
    sa.Column('source_document_id', sa.String(length=150), nullable=True),
    sa.Column('source_page', sa.String(length=30), nullable=True),
    sa.Column('intake_batch_id', sa.String(length=100), nullable=False),
    sa.Column('import_file_id', sa.String(length=100), nullable=False),
    sa.Column('raw_record_id', sa.String(length=100), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=False),
    sa.Column('source_file_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assertion_state', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('independence_status', sa.String(length=20), server_default=sa.text("'UNVERIFIED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            assertion_state IN (\n                'ACTIVE',\n                'SUPERSEDED',\n                'WITHDRAWN',\n                'DISPUTED'\n            )\n            ", name=op.f('ck_source_assertion_source_assertion_state')),
    sa.CheckConstraint("\n            independence_status IN (\n                'UNVERIFIED',\n                'INDEPENDENT',\n                'NOT_INDEPENDENT'\n            )\n            ", name=op.f('ck_source_assertion_source_assertion_independence')),
    sa.CheckConstraint("asserted_value <> '{}'::jsonb", name=op.f('ck_source_assertion_source_assertion_value_not_empty')),
    sa.CheckConstraint("jsonb_typeof(asserted_value) = 'object'", name=op.f('ck_source_assertion_source_assertion_value_object')),
    sa.CheckConstraint("source_file_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_assertion_source_assertion_valid_sha256')),
    sa.CheckConstraint('\n            length(trim(intake_batch_id)) > 0\n            AND length(trim(import_file_id)) > 0\n            AND length(trim(raw_record_id)) > 0\n            AND length(trim(source_file_name)) > 0\n            ', name=op.f('ck_source_assertion_source_assertion_provenance_ids')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_source_assertion_source_assertion_transaction_period')),
    sa.CheckConstraint('source_row_number IS NULL OR source_row_number > 0', name=op.f('ck_source_assertion_source_assertion_positive_row_number')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_source_assertion_source_assertion_valid_period')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_source_assertion_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['identity.source_system.source_system_id'], name=op.f('fk_source_assertion_source_system_id_source_system'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('source_assertion_id', name=op.f('pk_source_assertion')),
    schema='identity'
    )
    op.create_index('ix_source_assertion_officer_type', 'source_assertion', ['officer_uid', 'assertion_type'], unique=False, schema='identity')
    op.create_table('officer_address_version',
    sa.Column('address_version_id', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_address_version_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('local_station_reference', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            address_type IN (\n                'PRESENT',\n                'PERMANENT',\n                'OTHER'\n            )\n            ", name=op.f('ck_officer_address_version_officer_address_type')),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED'\n            )\n            ", name=op.f('ck_officer_address_version_officer_address_record_state')),
    sa.CheckConstraint('\n            address_text IS NOT NULL\n            OR local_station_reference IS NOT NULL\n            ', name=op.f('ck_officer_address_version_officer_address_has_value')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_address_version_officer_address_transaction_period')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_officer_address_version_officer_address_valid_period')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_address_version_officer_address_positive_version')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_address_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_address_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_address_version_id'], ['identity.officer_address_version.address_version_id'], name=op.f('fk_officer_address_version_supersedes_address_version_id_officer_address_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('address_version_id', name=op.f('pk_officer_address_version')),
    sa.UniqueConstraint('officer_uid', 'address_type', 'version_number', name='uq_officer_address_type_version'),
    schema='identity'
    )
    op.create_index('ix_officer_address_valid_time', 'officer_address_version', ['officer_uid', 'address_type', 'valid_from', 'valid_to'], unique=False, schema='identity')
    op.create_table('officer_contact_version',
    sa.Column('contact_version_id', sa.UUID(), nullable=False),
    sa.Column('contact_chain_uid', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_contact_version_id', sa.UUID(), nullable=True),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_value_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('contact_lookup_hmac', sa.String(length=64), nullable=False),
    sa.Column('normalization_profile', sa.String(length=50), nullable=False),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=False),
    sa.Column('lookup_key_version', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED',\n                'WITHDRAWN'\n            )\n            ", name=op.f('ck_officer_contact_version_officer_contact_record_state')),
    sa.CheckConstraint("contact_lookup_hmac ~ '^[0-9a-f]{64}$'", name=op.f('ck_officer_contact_version_officer_contact_valid_lookup_hmac')),
    sa.CheckConstraint("contact_type IN ('EMAIL', 'MOBILE')", name=op.f('ck_officer_contact_version_officer_contact_type')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_contact_version_officer_contact_transaction_period')),
    sa.CheckConstraint('\n            valid_to IS NULL\n            OR valid_from IS NULL\n            OR valid_to >= valid_from\n            ', name=op.f('ck_officer_contact_version_officer_contact_valid_period')),
    sa.CheckConstraint('length(encryption_key_version) > 0', name=op.f('ck_officer_contact_version_officer_contact_encryption_key_version')),
    sa.CheckConstraint('length(lookup_key_version) > 0', name=op.f('ck_officer_contact_version_officer_contact_lookup_key_version')),
    sa.CheckConstraint('octet_length(contact_value_ciphertext) > 0', name=op.f('ck_officer_contact_version_officer_contact_has_ciphertext')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_contact_version_officer_contact_positive_version')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_contact_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_contact_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_contact_version_id'], ['identity.officer_contact_version.contact_version_id'], name=op.f('fk_officer_contact_version_supersedes_contact_version_id_officer_contact_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contact_version_id', name=op.f('pk_officer_contact_version')),
    sa.UniqueConstraint('contact_chain_uid', 'version_number', name='uq_officer_contact_chain_version'),
    schema='identity'
    )
    op.create_index('ix_officer_contact_lookup_hmac', 'officer_contact_version', ['contact_type', 'contact_lookup_hmac'], unique=False, schema='identity')
    op.create_index('ix_officer_contact_officer_type', 'officer_contact_version', ['officer_uid', 'contact_type'], unique=False, schema='identity')
    op.create_table('officer_demographic_version',
    sa.Column('demographic_version_id', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_demographic_version_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=250), nullable=True),
    sa.Column('nationality_code', sa.String(length=50), nullable=True),
    sa.Column('religion_code', sa.String(length=50), nullable=True),
    sa.Column('gender_code', sa.String(length=30), nullable=True),
    sa.Column('marital_status_code', sa.String(length=30), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED'\n            )\n            ", name=op.f('ck_officer_demographic_version_officer_demographic_record_state')),
    sa.CheckConstraint('\n            date_of_birth IS NOT NULL\n            OR place_of_birth IS NOT NULL\n            OR nationality_code IS NOT NULL\n            OR religion_code IS NOT NULL\n            OR gender_code IS NOT NULL\n            OR marital_status_code IS NOT NULL\n            ', name=op.f('ck_officer_demographic_version_officer_demographic_has_value')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_demographic_version_officer_demographic_transaction_period')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_officer_demographic_version_officer_demographic_valid_period')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_demographic_version_officer_demographic_positive_version')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_demographic_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_demographic_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_demographic_version_id'], ['identity.officer_demographic_version.demographic_version_id'], name=op.f('fk_officer_demographic_version_supersedes_demographic_version_id_officer_demographic_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('demographic_version_id', name=op.f('pk_officer_demographic_version')),
    sa.UniqueConstraint('officer_uid', 'version_number', name='uq_officer_demographic_version_number'),
    schema='identity'
    )
    op.create_index('ix_officer_demographic_valid_time', 'officer_demographic_version', ['officer_uid', 'valid_from', 'valid_to'], unique=False, schema='identity')
    op.create_table('officer_family_relation',
    sa.Column('family_relation_version_id', sa.UUID(), nullable=False),
    sa.Column('relation_chain_uid', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_family_relation_version_id', sa.UUID(), nullable=True),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('related_person_name', sa.String(length=300), nullable=False),
    sa.Column('related_person_gender_code', sa.String(length=30), nullable=True),
    sa.Column('related_person_date_of_birth', sa.Date(), nullable=True),
    sa.Column('related_person_place_of_birth', sa.String(length=250), nullable=True),
    sa.Column('related_person_address', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED'\n            )\n            ", name=op.f('ck_officer_family_relation_officer_family_record_state')),
    sa.CheckConstraint("\n            relationship_type IN (\n                'FATHER',\n                'MOTHER',\n                'SPOUSE',\n                'CHILD',\n                'GUARDIAN',\n                'OTHER'\n            )\n            ", name=op.f('ck_officer_family_relation_officer_family_relationship_type')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_family_relation_officer_family_transaction_period')),
    sa.CheckConstraint('length(trim(related_person_name)) > 0', name=op.f('ck_officer_family_relation_officer_family_related_person_name')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_officer_family_relation_officer_family_valid_period')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_family_relation_officer_family_positive_version')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_family_relation_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_family_relation_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_family_relation_version_id'], ['identity.officer_family_relation.family_relation_version_id'], name=op.f('fk_officer_family_relation_supersedes_family_relation_version_id_officer_family_relation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('family_relation_version_id', name=op.f('pk_officer_family_relation')),
    sa.UniqueConstraint('relation_chain_uid', 'version_number', name='uq_officer_family_chain_version'),
    schema='identity'
    )
    op.create_index('ix_officer_family_officer_relationship', 'officer_family_relation', ['officer_uid', 'relationship_type'], unique=False, schema='identity')
    op.create_table('officer_identifier_version',
    sa.Column('identifier_version_id', sa.UUID(), nullable=False),
    sa.Column('identifier_chain_uid', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_identifier_version_id', sa.UUID(), nullable=True),
    sa.Column('identifier_type', sa.String(length=30), nullable=False),
    sa.Column('identifier_value_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('identifier_lookup_hmac', sa.String(length=64), nullable=False),
    sa.Column('normalization_profile', sa.String(length=50), nullable=False),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=False),
    sa.Column('lookup_key_version', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            identifier_type IN (\n                'NIC',\n                'POLICE_ID',\n                'REGIMENTAL_NUMBER',\n                'TIN'\n            )\n            ", name=op.f('ck_officer_identifier_version_officer_identifier_type')),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED',\n                'WITHDRAWN'\n            )\n            ", name=op.f('ck_officer_identifier_version_officer_identifier_record_state')),
    sa.CheckConstraint("identifier_lookup_hmac ~ '^[0-9a-f]{64}$'", name=op.f('ck_officer_identifier_version_officer_identifier_valid_lookup_hmac')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_identifier_version_officer_identifier_transaction_period')),
    sa.CheckConstraint('\n            valid_to IS NULL\n            OR valid_from IS NULL\n            OR valid_to >= valid_from\n            ', name=op.f('ck_officer_identifier_version_officer_identifier_valid_period')),
    sa.CheckConstraint('length(encryption_key_version) > 0', name=op.f('ck_officer_identifier_version_officer_identifier_encryption_key_version')),
    sa.CheckConstraint('length(lookup_key_version) > 0', name=op.f('ck_officer_identifier_version_officer_identifier_lookup_key_version')),
    sa.CheckConstraint('octet_length(identifier_value_ciphertext) > 0', name=op.f('ck_officer_identifier_version_officer_identifier_has_ciphertext')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_identifier_version_officer_identifier_positive_version')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_identifier_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_identifier_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_identifier_version_id'], ['identity.officer_identifier_version.identifier_version_id'], name=op.f('fk_officer_identifier_version_supersedes_identifier_version_id_officer_identifier_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('identifier_version_id', name=op.f('pk_officer_identifier_version')),
    sa.UniqueConstraint('identifier_chain_uid', 'version_number', name='uq_officer_identifier_chain_version'),
    schema='identity'
    )
    op.create_index('ix_officer_identifier_lookup_hmac', 'officer_identifier_version', ['identifier_type', 'identifier_lookup_hmac'], unique=False, schema='identity')
    op.create_index('ix_officer_identifier_officer_type', 'officer_identifier_version', ['officer_uid', 'identifier_type'], unique=False, schema='identity')
    op.create_table('officer_name_version',
    sa.Column('name_version_id', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_name_version_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('name_with_initials', sa.String(length=250), nullable=True),
    sa.Column('initials', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED'\n            )\n            ", name=op.f('ck_officer_name_version_officer_name_record_state')),
    sa.CheckConstraint('\n            full_name IS NOT NULL\n            OR name_with_initials IS NOT NULL\n            ', name=op.f('ck_officer_name_version_officer_name_has_value')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_name_version_officer_name_transaction_period')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_officer_name_version_officer_name_valid_period')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_name_version_officer_name_positive_version')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_name_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_name_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_name_version_id'], ['identity.officer_name_version.name_version_id'], name=op.f('fk_officer_name_version_supersedes_name_version_id_officer_name_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('name_version_id', name=op.f('pk_officer_name_version')),
    sa.UniqueConstraint('officer_uid', 'version_number', name='uq_officer_name_version_number'),
    schema='identity'
    )
    op.create_index('ix_officer_name_valid_time', 'officer_name_version', ['officer_uid', 'valid_from', 'valid_to'], unique=False, schema='identity')
    op.create_table('officer_physical_profile_version',
    sa.Column('physical_profile_version_id', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_physical_profile_version_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chest_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('measured_at', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED'\n            )\n            ", name=op.f('ck_officer_physical_profile_version_officer_physical_profile_record_state')),
    sa.CheckConstraint('\n            height_cm IS NOT NULL\n            OR chest_cm IS NOT NULL\n            ', name=op.f('ck_officer_physical_profile_version_officer_physical_profile_has_value')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_physical_profile_version_officer_physical_profile_transaction_period')),
    sa.CheckConstraint('chest_cm IS NULL OR chest_cm > 0', name=op.f('ck_officer_physical_profile_version_officer_physical_profile_positive_chest')),
    sa.CheckConstraint('height_cm IS NULL OR height_cm > 0', name=op.f('ck_officer_physical_profile_version_officer_physical_profile_positive_height')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_officer_physical_profile_version_officer_physical_profile_valid_period')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_physical_profile_version_officer_physical_profile_positive_version')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_physical_profile_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_physical_profile_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_physical_profile_version_id'], ['identity.officer_physical_profile_version.physical_profile_version_id'], name=op.f('fk_officer_physical_profile_version_supersedes_physical_profile_version_id_officer_physical_profile_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('physical_profile_version_id', name=op.f('pk_officer_physical_profile_version')),
    sa.UniqueConstraint('officer_uid', 'version_number', name='uq_officer_physical_profile_version_number'),
    schema='identity'
    )
    op.create_index('ix_officer_physical_profile_valid_time', 'officer_physical_profile_version', ['officer_uid', 'valid_from', 'valid_to'], unique=False, schema='identity')
    op.create_table('officer_previous_employment_version',
    sa.Column('employment_version_id', sa.UUID(), nullable=False),
    sa.Column('employment_chain_uid', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_employment_version_id', sa.UUID(), nullable=True),
    sa.Column('employer_department_name', sa.String(length=300), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED',\n                'WITHDRAWN'\n            )\n            ", name=op.f('ck_officer_previous_employment_version_officer_previous_employment_record_state')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_previous_employment_version_officer_previous_employment_transaction_period')),
    sa.CheckConstraint('\n            valid_to IS NULL\n            OR valid_from IS NULL\n            OR valid_to >= valid_from\n            ', name=op.f('ck_officer_previous_employment_version_officer_previous_employment_valid_period')),
    sa.CheckConstraint('length(trim(employer_department_name)) > 0', name=op.f('ck_officer_previous_employment_version_officer_previous_employment_has_department')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_previous_employment_version_officer_previous_employment_positive_version')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_previous_employment_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_previous_employment_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_employment_version_id'], ['identity.officer_previous_employment_version.employment_version_id'], name=op.f('fk_officer_previous_employment_version_supersedes_employment_version_id_officer_previous_employment_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('employment_version_id', name=op.f('pk_officer_previous_employment_version')),
    sa.UniqueConstraint('employment_chain_uid', 'version_number', name='uq_officer_previous_employment_chain_version'),
    schema='identity'
    )
    op.create_index('ix_officer_previous_employment_officer', 'officer_previous_employment_version', ['officer_uid'], unique=False, schema='identity')
    op.create_index('ix_officer_previous_employment_valid_time', 'officer_previous_employment_version', ['officer_uid', 'valid_from', 'valid_to'], unique=False, schema='identity')
    op.create_table('officer_restricted_profile_version',
    sa.Column('restricted_profile_version_id', sa.UUID(), nullable=False),
    sa.Column('restricted_profile_chain_uid', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_restricted_profile_version_id', sa.UUID(), nullable=True),
    sa.Column('blood_group_code', sa.String(length=20), nullable=True),
    sa.Column('identifying_marks_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('medical_officer_remark_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED',\n                'WITHDRAWN'\n            )\n            ", name=op.f('ck_officer_restricted_profile_version_officer_restricted_profile_record_state')),
    sa.CheckConstraint('\n            (\n                identifying_marks_ciphertext IS NULL\n                AND medical_officer_remark_ciphertext IS NULL\n            )\n            OR (\n                encryption_key_version IS NOT NULL\n                AND length(encryption_key_version) > 0\n            )\n            ', name=op.f('ck_officer_restricted_profile_version_officer_restricted_profile_encryption_key')),
    sa.CheckConstraint('\n            blood_group_code IS NOT NULL\n            OR identifying_marks_ciphertext IS NOT NULL\n            OR medical_officer_remark_ciphertext IS NOT NULL\n            ', name=op.f('ck_officer_restricted_profile_version_officer_restricted_profile_has_value')),
    sa.CheckConstraint('\n            identifying_marks_ciphertext IS NULL\n            OR octet_length(identifying_marks_ciphertext) > 0\n            ', name=op.f('ck_officer_restricted_profile_version_officer_restricted_profile_identifying_marks')),
    sa.CheckConstraint('\n            medical_officer_remark_ciphertext IS NULL\n            OR octet_length(medical_officer_remark_ciphertext) > 0\n            ', name=op.f('ck_officer_restricted_profile_version_officer_restricted_profile_medical_remark')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_restricted_profile_version_officer_restricted_profile_transaction_period')),
    sa.CheckConstraint('\n            valid_to IS NULL\n            OR valid_from IS NULL\n            OR valid_to >= valid_from\n            ', name=op.f('ck_officer_restricted_profile_version_officer_restricted_profile_valid_period')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_restricted_profile_version_officer_restricted_profile_positive_version')),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_restricted_profile_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_restricted_profile_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_restricted_profile_version_id'], ['identity.officer_restricted_profile_version.restricted_profile_version_id'], name=op.f('fk_officer_restricted_profile_version_supersedes_restricted_profile_version_id_officer_restricted_profile_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('restricted_profile_version_id', name=op.f('pk_officer_restricted_profile_version')),
    sa.UniqueConstraint('restricted_profile_chain_uid', 'version_number', name='uq_officer_restricted_profile_chain_version'),
    schema='identity'
    )
    op.create_index('ix_officer_restricted_profile_officer', 'officer_restricted_profile_version', ['officer_uid'], unique=False, schema='identity')
    op.create_index('ix_officer_restricted_profile_valid_time', 'officer_restricted_profile_version', ['officer_uid', 'valid_from', 'valid_to'], unique=False, schema='identity')
    op.create_table('source_attestation',
    sa.Column('attestation_version_id', sa.UUID(), nullable=False),
    sa.Column('attestation_chain_uid', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('actor_officer_uid', sa.UUID(), nullable=True),
    sa.Column('supersedes_attestation_version_id', sa.UUID(), nullable=True),
    sa.Column('attestation_type', sa.String(length=20), nullable=False),
    sa.Column('actor_name_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('actor_identifier_type', sa.String(length=30), nullable=True),
    sa.Column('actor_identifier_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('actor_identifier_lookup_hmac', sa.String(length=64), nullable=True),
    sa.Column('actor_rank_asserted', sa.String(length=100), nullable=True),
    sa.Column('signature_reference_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('attested_on', sa.Date(), nullable=True),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=True),
    sa.Column('lookup_key_version', sa.String(length=50), nullable=True),
    sa.Column('resolution_status', sa.String(length=20), server_default=sa.text("'UNRESOLVED'"), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                resolution_status = 'RESOLVED'\n                AND actor_officer_uid IS NOT NULL\n            )\n            OR (\n                resolution_status <> 'RESOLVED'\n                AND actor_officer_uid IS NULL\n            )\n            ", name=op.f('ck_source_attestation_attestation_resolved_actor')),
    sa.CheckConstraint("\n            actor_identifier_lookup_hmac IS NULL\n            OR actor_identifier_lookup_hmac ~ '^[0-9a-f]{64}$'\n            ", name=op.f('ck_source_attestation_attestation_lookup_hmac')),
    sa.CheckConstraint("\n            actor_identifier_type IS NULL\n            OR actor_identifier_type IN (\n                'NIC',\n                'POLICE_ID',\n                'REGIMENTAL_NUMBER'\n            )\n            ", name=op.f('ck_source_attestation_attestation_identifier_type')),
    sa.CheckConstraint("\n            record_state IN (\n                'ACTIVE',\n                'SUPERSEDED',\n                'DISPUTED',\n                'WITHDRAWN'\n            )\n            ", name=op.f('ck_source_attestation_attestation_record_state')),
    sa.CheckConstraint("\n            resolution_status IN (\n                'UNRESOLVED',\n                'RESOLVED',\n                'AMBIGUOUS',\n                'NOT_SUPPLIED'\n            )\n            ", name=op.f('ck_source_attestation_attestation_resolution')),
    sa.CheckConstraint("attestation_type IN ('RECORDED_BY', 'CERTIFIED_BY')", name=op.f('ck_source_attestation_attestation_type')),
    sa.CheckConstraint('\n            (\n                actor_name_ciphertext IS NULL\n                AND actor_identifier_ciphertext IS NULL\n                AND signature_reference_ciphertext IS NULL\n            )\n            OR (\n                encryption_key_version IS NOT NULL\n                AND length(encryption_key_version) > 0\n            )\n            ', name=op.f('ck_source_attestation_attestation_encryption_key')),
    sa.CheckConstraint('\n            actor_identifier_ciphertext IS NULL\n            OR octet_length(actor_identifier_ciphertext) > 0\n            ', name=op.f('ck_source_attestation_attestation_actor_identifier')),
    sa.CheckConstraint('\n            actor_identifier_lookup_hmac IS NULL\n            OR (\n                lookup_key_version IS NOT NULL\n                AND length(lookup_key_version) > 0\n                AND actor_identifier_type IS NOT NULL\n            )\n            ', name=op.f('ck_source_attestation_attestation_lookup_key')),
    sa.CheckConstraint('\n            actor_name_ciphertext IS NULL\n            OR octet_length(actor_name_ciphertext) > 0\n            ', name=op.f('ck_source_attestation_attestation_actor_name')),
    sa.CheckConstraint('\n            actor_officer_uid IS NOT NULL\n            OR actor_name_ciphertext IS NOT NULL\n            OR actor_identifier_ciphertext IS NOT NULL\n            OR actor_rank_asserted IS NOT NULL\n            OR signature_reference_ciphertext IS NOT NULL\n            OR attested_on IS NOT NULL\n            ', name=op.f('ck_source_attestation_attestation_has_value')),
    sa.CheckConstraint('\n            signature_reference_ciphertext IS NULL\n            OR octet_length(signature_reference_ciphertext) > 0\n            ', name=op.f('ck_source_attestation_attestation_signature')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_source_attestation_attestation_transaction_period')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_source_attestation_attestation_positive_version')),
    sa.ForeignKeyConstraint(['actor_officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_source_attestation_actor_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_source_attestation_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_attestation_version_id'], ['identity.source_attestation.attestation_version_id'], name=op.f('fk_source_attestation_supersedes_attestation_version_id_source_attestation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('attestation_version_id', name=op.f('pk_source_attestation')),
    sa.UniqueConstraint('attestation_chain_uid', 'version_number', name='uq_source_attestation_chain_version'),
    schema='identity'
    )
    op.create_index('ix_source_attestation_actor', 'source_attestation', ['actor_officer_uid'], unique=False, schema='identity')
    op.create_index('ix_source_attestation_assertion', 'source_attestation', ['source_assertion_id'], unique=False, schema='identity')
    op.create_table('officer_family_civil_event_version',
    sa.Column('civil_event_version_id', sa.UUID(), nullable=False),
    sa.Column('civil_event_chain_uid', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('family_relation_version_id', sa.UUID(), nullable=False),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_civil_event_version_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('evidence_reference_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED',\n                'WITHDRAWN'\n            )\n            ", name=op.f('ck_officer_family_civil_event_version_officer_family_civil_event_record_state')),
    sa.CheckConstraint("event_type IN ('MARRIAGE', 'DIVORCE', 'DEATH')", name=op.f('ck_officer_family_civil_event_version_officer_family_civil_event_type')),
    sa.CheckConstraint('\n            event_date IS NOT NULL\n            OR evidence_reference_ciphertext IS NOT NULL\n            ', name=op.f('ck_officer_family_civil_event_version_officer_family_civil_event_has_value')),
    sa.CheckConstraint('\n            evidence_reference_ciphertext IS NULL\n            OR (\n                encryption_key_version IS NOT NULL\n                AND length(encryption_key_version) > 0\n            )\n            ', name=op.f('ck_officer_family_civil_event_version_officer_family_civil_event_encryption_key')),
    sa.CheckConstraint('\n            evidence_reference_ciphertext IS NULL\n            OR octet_length(evidence_reference_ciphertext) > 0\n            ', name=op.f('ck_officer_family_civil_event_version_officer_family_civil_event_evidence_reference')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_family_civil_event_version_officer_family_civil_event_transaction_period')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_family_civil_event_version_officer_family_civil_event_positive_version')),
    sa.ForeignKeyConstraint(['family_relation_version_id'], ['identity.officer_family_relation.family_relation_version_id'], name=op.f('fk_officer_family_civil_event_version_family_relation_version_id_officer_family_relation'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_family_civil_event_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_family_civil_event_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_civil_event_version_id'], ['identity.officer_family_civil_event_version.civil_event_version_id'], name=op.f('fk_officer_family_civil_event_version_supersedes_civil_event_version_id_officer_family_civil_event_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('civil_event_version_id', name=op.f('pk_officer_family_civil_event_version')),
    sa.UniqueConstraint('civil_event_chain_uid', 'version_number', name='uq_officer_family_civil_event_chain_version'),
    schema='identity'
    )
    op.create_index('ix_officer_family_civil_event_date', 'officer_family_civil_event_version', ['officer_uid', 'event_date'], unique=False, schema='identity')
    op.create_index('ix_officer_family_civil_event_officer_type', 'officer_family_civil_event_version', ['officer_uid', 'event_type'], unique=False, schema='identity')
    op.create_table('officer_next_of_kin_version',
    sa.Column('next_of_kin_version_id', sa.UUID(), nullable=False),
    sa.Column('next_of_kin_chain_uid', sa.UUID(), nullable=False),
    sa.Column('officer_uid', sa.UUID(), nullable=False),
    sa.Column('family_relation_version_id', sa.UUID(), nullable=True),
    sa.Column('source_assertion_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_next_of_kin_version_id', sa.UUID(), nullable=True),
    sa.Column('related_person_name', sa.String(length=300), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('address_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('transaction_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_state', sa.String(length=20), server_default=sa.text("'ASSERTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            record_state IN (\n                'ASSERTED',\n                'ACCEPTED',\n                'SUPERSEDED',\n                'DISPUTED',\n                'WITHDRAWN'\n            )\n            ", name=op.f('ck_officer_next_of_kin_version_officer_next_of_kin_record_state')),
    sa.CheckConstraint('\n            address_ciphertext IS NULL\n            OR (\n                encryption_key_version IS NOT NULL\n                AND length(encryption_key_version) > 0\n            )\n            ', name=op.f('ck_officer_next_of_kin_version_officer_next_of_kin_encryption_key')),
    sa.CheckConstraint('\n            address_ciphertext IS NULL\n            OR octet_length(address_ciphertext) > 0\n            ', name=op.f('ck_officer_next_of_kin_version_officer_next_of_kin_address')),
    sa.CheckConstraint('\n            transaction_end IS NULL\n            OR transaction_end > transaction_start\n            ', name=op.f('ck_officer_next_of_kin_version_officer_next_of_kin_transaction_period')),
    sa.CheckConstraint('\n            valid_to IS NULL\n            OR valid_from IS NULL\n            OR valid_to >= valid_from\n            ', name=op.f('ck_officer_next_of_kin_version_officer_next_of_kin_valid_period')),
    sa.CheckConstraint('length(trim(related_person_name)) > 0', name=op.f('ck_officer_next_of_kin_version_officer_next_of_kin_has_name')),
    sa.CheckConstraint('length(trim(relationship_type)) > 0', name=op.f('ck_officer_next_of_kin_version_officer_next_of_kin_has_relationship')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_officer_next_of_kin_version_officer_next_of_kin_positive_version')),
    sa.ForeignKeyConstraint(['family_relation_version_id'], ['identity.officer_family_relation.family_relation_version_id'], name=op.f('fk_officer_next_of_kin_version_family_relation_version_id_officer_family_relation'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['officer_uid'], ['identity.officer.officer_uid'], name=op.f('fk_officer_next_of_kin_version_officer_uid_officer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_assertion_id'], ['identity.source_assertion.source_assertion_id'], name=op.f('fk_officer_next_of_kin_version_source_assertion_id_source_assertion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_next_of_kin_version_id'], ['identity.officer_next_of_kin_version.next_of_kin_version_id'], name=op.f('fk_officer_next_of_kin_version_supersedes_next_of_kin_version_id_officer_next_of_kin_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('next_of_kin_version_id', name=op.f('pk_officer_next_of_kin_version')),
    sa.UniqueConstraint('next_of_kin_chain_uid', 'version_number', name='uq_officer_next_of_kin_chain_version'),
    schema='identity'
    )
    op.create_index('ix_officer_next_of_kin_officer', 'officer_next_of_kin_version', ['officer_uid'], unique=False, schema='identity')
    op.create_index('ix_officer_next_of_kin_valid_time', 'officer_next_of_kin_version', ['officer_uid', 'valid_from', 'valid_to'], unique=False, schema='identity')
    # Grant the identity application only the data operations it requires.
    # The Alembic version table is intentionally excluded.
    op.execute(
        sa.text(
            """
            DO $$
            DECLARE
                table_record RECORD;
            BEGIN
                FOR table_record IN
                    SELECT tablename
                    FROM pg_tables
                    WHERE schemaname = 'identity'
                      AND tablename <> 'alembic_version'
                LOOP
                    EXECUTE format(
                        'GRANT SELECT, INSERT, UPDATE '
                        'ON TABLE identity.%I '
                        'TO police_identity_app',
                        table_record.tablename
                    );
                END LOOP;
            END
            $$;
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
        # Remove application privileges before dropping identity tables.
    op.execute(
        sa.text(
            """
            DO $$
            DECLARE
                table_record RECORD;
            BEGIN
                FOR table_record IN
                    SELECT tablename
                    FROM pg_tables
                    WHERE schemaname = 'identity'
                      AND tablename <> 'alembic_version'
                LOOP
                    EXECUTE format(
                        'REVOKE ALL PRIVILEGES '
                        'ON TABLE identity.%I '
                        'FROM police_identity_app',
                        table_record.tablename
                    );
                END LOOP;
            END
            $$;
            """
        )
    )
    op.drop_index('ix_officer_next_of_kin_valid_time', table_name='officer_next_of_kin_version', schema='identity')
    op.drop_index('ix_officer_next_of_kin_officer', table_name='officer_next_of_kin_version', schema='identity')
    op.drop_table('officer_next_of_kin_version', schema='identity')
    op.drop_index('ix_officer_family_civil_event_officer_type', table_name='officer_family_civil_event_version', schema='identity')
    op.drop_index('ix_officer_family_civil_event_date', table_name='officer_family_civil_event_version', schema='identity')
    op.drop_table('officer_family_civil_event_version', schema='identity')
    op.drop_index('ix_source_attestation_assertion', table_name='source_attestation', schema='identity')
    op.drop_index('ix_source_attestation_actor', table_name='source_attestation', schema='identity')
    op.drop_table('source_attestation', schema='identity')
    op.drop_index('ix_officer_restricted_profile_valid_time', table_name='officer_restricted_profile_version', schema='identity')
    op.drop_index('ix_officer_restricted_profile_officer', table_name='officer_restricted_profile_version', schema='identity')
    op.drop_table('officer_restricted_profile_version', schema='identity')
    op.drop_index('ix_officer_previous_employment_valid_time', table_name='officer_previous_employment_version', schema='identity')
    op.drop_index('ix_officer_previous_employment_officer', table_name='officer_previous_employment_version', schema='identity')
    op.drop_table('officer_previous_employment_version', schema='identity')
    op.drop_index('ix_officer_physical_profile_valid_time', table_name='officer_physical_profile_version', schema='identity')
    op.drop_table('officer_physical_profile_version', schema='identity')
    op.drop_index('ix_officer_name_valid_time', table_name='officer_name_version', schema='identity')
    op.drop_table('officer_name_version', schema='identity')
    op.drop_index('ix_officer_identifier_officer_type', table_name='officer_identifier_version', schema='identity')
    op.drop_index('ix_officer_identifier_lookup_hmac', table_name='officer_identifier_version', schema='identity')
    op.drop_table('officer_identifier_version', schema='identity')
    op.drop_index('ix_officer_family_officer_relationship', table_name='officer_family_relation', schema='identity')
    op.drop_table('officer_family_relation', schema='identity')
    op.drop_index('ix_officer_demographic_valid_time', table_name='officer_demographic_version', schema='identity')
    op.drop_table('officer_demographic_version', schema='identity')
    op.drop_index('ix_officer_contact_officer_type', table_name='officer_contact_version', schema='identity')
    op.drop_index('ix_officer_contact_lookup_hmac', table_name='officer_contact_version', schema='identity')
    op.drop_table('officer_contact_version', schema='identity')
    op.drop_index('ix_officer_address_valid_time', table_name='officer_address_version', schema='identity')
    op.drop_table('officer_address_version', schema='identity')
    op.drop_index('ix_source_assertion_officer_type', table_name='source_assertion', schema='identity')
    op.drop_table('source_assertion', schema='identity')
    op.drop_table('source_system', schema='identity')
    op.drop_table('officer', schema='identity')
    # ### end Alembic commands ###
