"""create protected intake staging tables

Revision ID: d25819f4b100
Revises: 8757cc30d835
Create Date: 2026-10-05 19:37:56.235551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd25819f4b100'
down_revision: Union[str, Sequence[str], None] = '8757cc30d835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create protected intake storage and its restricted grants."""

    # Fail if staging already exists rather than adopting an unknown schema.
    op.execute(
        "CREATE SCHEMA staging AUTHORIZATION police_identity_migrator"
    )
    op.execute("REVOKE ALL ON SCHEMA staging FROM PUBLIC")
    op.execute("REVOKE ALL ON SCHEMA staging FROM police_identity_app")
    op.execute("GRANT USAGE ON SCHEMA staging TO police_identity_app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_batch',
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('archive_sha256', sa.String(length=64), nullable=False),
    sa.Column('archive_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('expected_file_count', sa.Integer(), nullable=False),
    sa.Column('registration_receipt_id', sa.UUID(), nullable=False),
    sa.Column('registration_receipt_sha256', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("archive_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_intake_batch_archive_sha256')),
    sa.CheckConstraint("registration_receipt_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_intake_batch_receipt_sha256')),
    sa.CheckConstraint("schema_version = '1.0'", name=op.f('ck_intake_batch_supported_batch_schema')),
    sa.CheckConstraint('archive_size_bytes > 0 AND expected_file_count > 0', name=op.f('ck_intake_batch_positive_batch_sizes')),
    sa.CheckConstraint('length(trim(batch_id)) > 0', name=op.f('ck_intake_batch_batch_id_not_empty')),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_intake_batch')),
    schema='staging'
    )
    op.create_table('intake_file',
    sa.Column('import_file_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('archive_path', sa.Text(), nullable=False),
    sa.Column('source_file_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('expected_row_count', sa.BigInteger(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('declared_encoding', sa.String(length=20), nullable=False),
    sa.Column('delimiter', sa.String(length=1), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("declared_encoding IN ('UTF-8', 'UTF-8-BOM')", name=op.f('ck_intake_file_supported_encoding')),
    sa.CheckConstraint("delimiter = ','", name=op.f('ck_intake_file_supported_delimiter')),
    sa.CheckConstraint("jsonb_typeof(columns) = 'array'", name=op.f('ck_intake_file_columns_array')),
    sa.CheckConstraint("source_file_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_intake_file_file_sha256')),
    sa.CheckConstraint('jsonb_array_length(columns) = column_count', name=op.f('ck_intake_file_columns_count_matches')),
    sa.CheckConstraint('length(trim(archive_path)) > 0', name=op.f('ck_intake_file_file_path_not_empty')),
    sa.CheckConstraint('size_bytes > 0 AND expected_row_count >= 0 AND column_count > 0', name=op.f('ck_intake_file_valid_file_counts')),
    sa.ForeignKeyConstraint(['batch_id'], ['staging.intake_batch.batch_id'], name=op.f('fk_intake_file_batch_id_intake_batch'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('import_file_id', name=op.f('pk_intake_file')),
    sa.UniqueConstraint('batch_id', 'archive_path', name='uq_intake_file_batch_path'),
    sa.UniqueConstraint('import_file_id', 'batch_id', 'archive_path', 'source_file_sha256', name='uq_intake_file_source_binding'),
    schema='staging'
    )
    op.create_table('raw_record',
    sa.Column('raw_record_id', sa.String(length=64), nullable=False),
    sa.Column('import_file_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('archive_path', sa.Text(), nullable=False),
    sa.Column('source_file_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_row_number', sa.BigInteger(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('payload_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=False),
    sa.Column('staged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("raw_record_id ~ '^[0-9a-f]{64}$'", name=op.f('ck_raw_record_record_id_format')),
    sa.CheckConstraint("schema_version = '1.0'", name=op.f('ck_raw_record_supported_record_schema')),
    sa.CheckConstraint("source_file_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_raw_record_record_source_sha256')),
    sa.CheckConstraint('length(trim(encryption_key_version)) > 0', name=op.f('ck_raw_record_key_version_not_empty')),
    sa.CheckConstraint('octet_length(payload_ciphertext) > 28', name=op.f('ck_raw_record_ciphertext_envelope_length')),
    sa.CheckConstraint('source_row_number > 0', name=op.f('ck_raw_record_positive_record_number')),
    sa.ForeignKeyConstraint(['import_file_id', 'batch_id', 'archive_path', 'source_file_sha256'], ['staging.intake_file.import_file_id', 'staging.intake_file.batch_id', 'staging.intake_file.archive_path', 'staging.intake_file.source_file_sha256'], name='fk_raw_record_registered_source', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('raw_record_id', name=op.f('pk_raw_record')),
    sa.UniqueConstraint('import_file_id', 'source_row_number', name='uq_raw_record_file_row'),
    schema='staging'
    )
    # ### end Alembic commands ###



    # Grant only read and append operations to the application account.
    # Explicit revocation also clears any inherited default direct grants.
    for table_name in ("intake_batch", "intake_file", "raw_record"):
        op.execute(
            f"REVOKE ALL ON TABLE staging.{table_name} FROM PUBLIC"
        )
        op.execute(
            f"REVOKE ALL ON TABLE staging.{table_name} "
            "FROM police_identity_app"
        )
        op.execute(
            f"GRANT SELECT, INSERT ON TABLE staging.{table_name} "
            "TO police_identity_app"
        )


def downgrade() -> None:
    """Remove staging only when no registered evidence exists."""

    # Block concurrent writes while checking whether removal is safe.
    op.execute(
        "LOCK TABLE staging.intake_batch, staging.intake_file, "
        "staging.raw_record IN ACCESS EXCLUSIVE MODE"
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM staging.intake_batch)
               OR EXISTS (SELECT 1 FROM staging.intake_file)
               OR EXISTS (SELECT 1 FROM staging.raw_record)
            THEN
                RAISE EXCEPTION
                    'Cannot downgrade populated staging; preserve evidence first.';
            END IF;
        END;
        $$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_record', schema='staging')
    op.drop_table('intake_file', schema='staging')
    op.drop_table('intake_batch', schema='staging')
    # ### end Alembic commands ###

    # The generated statements above remove the three empty tables first.
    op.execute("DROP SCHEMA staging")
